# Regenerates the imported conformance corpora from the prior projects' test suites.
#
#   elixir scripts/import_corpus.exs
#
# It meta-parses each source suite, extracts the first string-literal argument of every
# `assert_conforms(...)` (parser) / `tokenize(...)` (lexer) call, tags each input by its enclosing
# `describe` title, dedups, and writes two GENERATED modules under test/support. We keep ONLY the
# input strings — the suites' own expectations (metadata-rich AST / exact `:elixir_tokenizer`
# tuples) are not Toxic2's contract; the live oracle is the arbiter. Output is committed; rerun
# this only when the upstream suites change.

parser_src = Path.expand("../../toxic_parser/test/conformance_test.exs", __DIR__)
lexer_src = Path.expand("../../toxic/test/toxic/valid_code_test.exs", __DIR__)
out_dir = Path.expand("../test/support", __DIR__)

# Pull a static binary out of a call argument. Plain string literals and `~s`/`~S` sigils with a
# single static fragment are taken; interpolated / computed args are skipped.
literal = fn
  bin, _self when is_binary(bin) ->
    {:ok, bin}

  {sig, _, [{:<<>>, _, [bin]}, _]}, _self when sig in [:sigil_s, :sigil_S] and is_binary(bin) ->
    {:ok, bin}

  _other, _self ->
    :skip
end

slug = fn title ->
  title
  |> String.downcase()
  |> String.replace(~r/[^a-z0-9]+/, "_")
  |> String.trim("_")
  |> case do
    "" -> "ungrouped"
    s -> s
  end
end

line_of = fn meta -> Keyword.get(meta, :line, 0) end

collect = fn path, call_name ->
  ast = path |> File.read!() |> Code.string_to_quoted!(columns: true)

  # describes by line, so each call can be attributed to the nearest preceding `describe`.
  {_, describes} =
    Macro.prewalk(ast, [], fn
      {:describe, meta, [title | _]} = node, acc when is_binary(title) ->
        {node, [{line_of.(meta), title} | acc]}

      node, acc ->
        {node, acc}
    end)

  describes = Enum.sort_by(describes, &elem(&1, 0))

  group_for = fn line ->
    describes
    |> Enum.take_while(fn {dl, _} -> dl <= line end)
    |> List.last()
    |> case do
      nil -> "ungrouped"
      {_, title} -> title
    end
  end

  {_, raw} =
    Macro.prewalk(ast, [], fn
      {^call_name, meta, [arg | _]} = node, acc ->
        case literal.(arg, literal) do
          {:ok, src} -> {node, [{src, line_of.(meta), group_for.(line_of.(meta))} | acc]}
          :skip -> {node, acc}
        end

      node, acc ->
        {node, acc}
    end)

  # Dedup on source, keeping the first occurrence (lowest line).
  raw
  |> Enum.sort_by(fn {_s, line, _g} -> line end)
  |> Enum.uniq_by(fn {s, _l, _g} -> s end)
end

render = fn module, source_file, entries ->
  body =
    Enum.map_join(entries, ",\n", fn {src, line, group} ->
      "    %{source: #{inspect(src)}, tags: #{inspect([:imported, String.to_atom(slug.(group))])}, " <>
        "group: #{inspect(group)}, line: #{line}}"
    end)

  """
  defmodule #{module} do
    @moduledoc false
    # GENERATED by scripts/import_corpus.exs from #{source_file}.
    # Do not edit by hand — rerun the generator. Only the input strings are imported; the live
    # oracle (not any captured expectation) is the conformance arbiter.

    @entries [
  #{body}
    ]

    @spec all() :: [%{source: String.t(), tags: [atom()], group: String.t(), line: pos_integer()}]
    def all, do: @entries
  end
  """
end

write = fn name, source ->
  File.write!(Path.join(out_dir, name), Code.format_string!(source) ++ ["\n"])
end

parser = collect.(parser_src, :assert_conforms)
lexer = collect.(lexer_src, :tokenize)

write.(
  "imported_parser_corpus.ex",
  render.("Toxic2.Conformance.ImportedParser", "toxic_parser/test/conformance_test.exs", parser)
)

write.(
  "imported_lexer_corpus.ex",
  render.("Toxic2.Conformance.ImportedLexer", "toxic/test/toxic/valid_code_test.exs", lexer)
)

IO.puts("imported parser corpus: #{length(parser)} unique sources")
IO.puts("imported lexer  corpus: #{length(lexer)} unique sources")
